config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'schedules#index'
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :memo, length: { maximum: 500 }

  validate :start_date_before_end_date

  private

  def start_date_before_end_date
    return if start_date.blank? || end_date.blank?

    if start_date > end_date
      errors.add(:end_date, "は、開始日以降の日付としてください。")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update, :show, :destroy]

  def index
    @schedules = Schedule.all
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:success] = "スケジュールが作成されました。"
      redirect_to @schedule
    else
      flash[:danger] = "スケジュール作成に失敗しました。"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      flash[:success] = "スケジュールが更新されました。"
      redirect_to @schedule
    else
      flash[:danger] = "スケジュール更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    # @schedule.destroy!
    flash[:success] = 'スケジュールが削除されました。'
    redirect_to schedules_path
  end

  private

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div>
      <h2><%= pluralize(schedule.errors.count, "エラー") %></h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :all_day %>
    <%= form.check_box :all_day %>
  </div>

  <div>
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div>
    <%= link_to "キャンセル", schedules_path %>
    <%= form.submit "保存" %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<%= render partial: 'form', locals: { schedule: @schedule, form_title: 'Edit Schedule' } %>

app/views/schedules/index.html.erb
<div>
  <div>予定一覧</div>
  <div><%= link_to "新規追加", new_schedule_path %></div>
</div>
<table>
  <% @schedules.each do |schedule| %>
  <tr>
    <td>ID</td>
    <td>タイトル</td>
    <td>開始日</td>
    <td>終了日</td>
    <td>終日</td>
    <td>更新日時</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><%= schedule.id %></td>
    <td><%= schedule.title %></td>
    <td><%= schedule.start_date.strftime("%Y/%m/%d") %></td>
    <td><%= schedule.end_date.strftime("%Y/%m/%d") %></td>
    <td><%= schedule.all_day ? "○" : ""  %></td>
    <td><%= schedule.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
    <td><%= link_to "詳細", schedule_path(schedule), class: 'btn btn-success' %></td>
    <td><%= link_to "編集", edit_schedule_path(schedule), class: 'btn btn-info' %></td>
    <td>
      <button data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal" data-bs-id="<%= schedule.id %>" class="btn btn-danger">削除</button>
    </td>
  </tr>
  <% end %>
</table>

<div>
  <div>
    <p>予定合計 <%= @schedules.size %>件</p>
  </div>
  <div>
    <p>本日の日付 <%= Date.current.strftime("%Y/%m/%d") %></p>
  </div>
</div>


<!-- 削除確認モーダル -->
<!-- Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteConfirmationModalLabel">削除確認</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        本当に削除してよろしいですか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除', "#", method: :delete, class: 'btn btn-danger', id: 'deleteBtn' %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<%= render partial: 'form', locals: { schedule: @schedule, form_title: 'New Schedule' } %>

app/views/schedules/show.html.erb
<div>
  <%= link_to "一覧に戻る", schedules_path %>
</div>
<div>
  <div><%= @schedule.title %></div>
  <div><%= link_to "編集", edit_schedule_path(@schedule) %></div>
</div>

<div>
  <div>開始日 <%= @schedule.start_date.strftime("%Y/%m/%d") %></div>
  <div>終了日 <%= @schedule.end_date.strftime("%Y/%m/%d") %></div>
  <div>終日 <%= @schedule.all_day ? "○" : "" %></div>
  <div>スケジュールメモ <%= @schedule.memo %></div>
</div>